All RSVPed Guests See The List of RSVPs
kernel-community/convo-app pull request #135
Opened 2024-01-20 23:28 UTC by Kanika1799

2024-01-27 02:51 UTC, anggxyz commented on src/components/EventPage/RsvpSection.tsx
> +                  <summary className="flex cursor-pointer list-none items-center justify-between font-medium">
this should be outside the `map`

2024-01-27 02:51 UTC, anggxyz commented on src/components/EventPage/RsvpSection.tsx
> +                    See All Rsvps list <TransitioningArrow />
this should be outside the `map`. is displaying the accordion as many times as the number of rsvps
<img width="430" alt="image" src="https://github.com/anggxyz/convo-app/assets/10832414/9a225a94-6a3b-4c24-9ad6-3e408d971dd3">

2024-01-27 02:52 UTC, anggxyz commented
can we use the component we already have? so it's easier to update/fix later
<img width="463" alt="image" src="https://github.com/anggxyz/convo-app/assets/10832414/2a445746-6084-403a-a5e2-83137b998606">

2024-01-27 02:54 UTC, anggxyz commented
ty for the PR btw! ❤️ I appreciate you working on the issue :)

2024-02-05 22:22 UTC, anggxyz commented on src/components/EventPage/RsvpSection.tsx
> +        <SessionsDetailsNonSubmittable sessions={sessions} />
this needs to be inside a check that checks for currently logged in user. if the user is signed out the component should not be visible. then it needs to check if the user has already RSVPd to one of the events in the current convo. only then the component should be visible

2024-02-05 22:23 UTC, anggxyz requested changes

2024-02-05 22:23 UTC, anggxyz commented on src/components/EventPage/RsvpSection.tsx
> +        <SessionsDetailsNonSubmittable sessions={sessions} />
and if the checks pass, this component should replace the above component with an option to remove RSVP if the user wants

2024-02-09 16:06 UTC, avirajkhare00 commented
Great PR

2024-02-21 02:41 UTC, merged